version: "3.4"


services:
  app:
    image: task
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: debug
      DB_DSN: postgresql://task:task@db:5432/task
      # just some urandom value for convenience
      JWT_SECRET: "264c66c41a1ac3b82d4fd93991de75cc740f6bcc94062e5719fa14bf842d7c45"
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: task
      POSTGRES_DB: task
    ports:
      - 5433:5432

  migrations:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db/task -schemas=task -user=task -password=task -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
